export type IssueCategory = 'broken_roads' | 'open_potholes' | 'electricity_poles' | 'sanitation';

export interface IssueCategoryInfo {
  id: IssueCategory;
  label: string;
  icon: string;
  description: string;
  color: string;
  bgLight: string;
  borderColor: string;
}

export type IssueStatus = 'reported' | 'validated' | 'in_progress' | 'resolved';

export interface TimelineEvent {
  id: string;
  status: IssueStatus;
  title: string;
  description: string;
  updatedBy: string;
  createdAt: string;
}

export interface Comment {
  id: string;
  userName: string;
  userEmail: string;
  text: string;
  createdAt: string;
}

export interface Issue {
  id: string;
  title: string;
  description: string;
  category: IssueCategory;
  status: IssueStatus;
  locationName: string;
  neighborhood: string;
  latitude: number; // 0-100 relative to map grid
  longitude: number; // 0-100 relative to map grid
  reporterName: string;
  reporterEmail: string;
  createdAt: string;
  updatedAt: string;
  validations: string[]; // List of user emails who validated
  flags: string[]; // List of user emails who flagged
  gravityScore: number; // 1-10, auto-suggested by Gemini
  gravityJustification: string; // generated by Gemini
  actionSteps: string[]; // suggested by Gemini
  officialRequestDraft: string; // generated by Gemini
  comments: Comment[];
  timeline: TimelineEvent[];
  photoUrl?: string; // Standard placeholder or mock image URL
  resolutionNotes?: string;
  resolvedAt?: string;
}

export interface NeighborhoodData {
  id: string;
  name: string;
  path: string; // SVG path coordinate data
  color: string;
  center: { x: number; y: number };
}

export interface CivicStats {
  totalIssues: number;
  resolvedIssues: number;
  activeIssues: number;
  validationCount: number;
  averageResolutionDays: number;
  categoryDistribution: Record<IssueCategory, number>;
  neighborhoodDistribution: Record<string, number>;
  statusDistribution: Record<IssueStatus, number>;
}

export interface LeaderboardUser {
  name: string;
  email: string;
  reportsCount: number;
  validationsCount: number;
  commentsCount: number;
  score: number;
  badge: string;
}
